// Roster: 23 parody fighters. Stats are 1-10.
// Body archetypes and outfit colors drive bodyPresets.js.
// Special attacks are dispatched via SpecialFX.jsx keyed by `specialFx`.

export const ROSTER = [
  // --- INDIAN POLITICAL ---
  { id: "modi", name: "Narendra Modi", tag: "PM 56\"", origin: "India",
    stats: { power: 8, speed: 6, defense: 8 },
    specialName: "Digital Vande Bharat Charge",
    specialDesc: "Golden aura charge + spectral bullet train slams through the enemy.",
    specialFx: "bulletTrain",
    palette: { skin: "#c68b5a", hair: "#e9e9e9", beard: "#d9d9d9", outfit: "#e2e2e2", accent: "#3a5f3a" },
    build: "stocky", accessory: "modiJacket" },
  { id: "yogi", name: "Yogi Adityanath", tag: "Baba Bulldozer", origin: "India",
    stats: { power: 9, speed: 5, defense: 9 },
    specialName: "Bulldozer Smash",
    specialDesc: "Leaps and drops a spectral bulldozer on the enemy.",
    specialFx: "bulldozer",
    palette: { skin: "#c68b5a", hair: "#111111", beard: null, outfit: "#f28c1a", accent: "#c15a00" },
    build: "compact", accessory: "monkRobe" },
  { id: "shah", name: "Amit Shah", tag: "Chanakya", origin: "India",
    stats: { power: 8, speed: 5, defense: 9 },
    specialName: "Chanakya Checkmate",
    specialDesc: "Traps attackers in an energy grid then shockwave palm.",
    specialFx: "checkmate",
    palette: { skin: "#c48b5c", hair: "#dcdcdc", beard: "#dcdcdc", outfit: "#f7f0e0", accent: "#8a5a2b" },
    build: "heavy", accessory: "shawl" },
  { id: "mamata", name: "Mamata Banerjee", tag: "Didi", origin: "India",
    stats: { power: 6, speed: 7, defense: 6 },
    specialName: "Khela Hobe Whirlwind",
    specialDesc: "Hurricane kick with blue protest shockwaves.",
    specialFx: "whirlwind",
    palette: { skin: "#c68b5a", hair: "#2a2a2a", beard: null, outfit: "#ffffff", accent: "#2a6bd6" },
    build: "slim", accessory: "saree" },
  { id: "rahul", name: "Rahul Gandhi", tag: "Bharat Jodo", origin: "India",
    stats: { power: 7, speed: 8, defense: 6 },
    specialName: "Bharat Jodo Punch Rush",
    specialDesc: "10-hit boxing combo, ends with a globe-energy uppercut.",
    specialFx: "punchRush",
    palette: { skin: "#c68b5a", hair: "#1a1a1a", beard: "#3a2a1a", outfit: "#ffffff", accent: "#c74a4a" },
    build: "athletic", accessory: "rolledSleeves" },
  { id: "kejriwal", name: "Arvind Kejriwal", tag: "Mufflerman", origin: "India",
    stats: { power: 6, speed: 6, defense: 8 },
    specialName: "Free Bijli Surge",
    specialDesc: "360° high-voltage electric shockwave ring.",
    specialFx: "electricRing",
    palette: { skin: "#c68b5a", hair: "#1a1a1a", beard: "#2a2a2a", outfit: "#3a3a4a", accent: "#c74a4a" },
    build: "average", accessory: "muffler" },
  { id: "dhruv", name: "Dhruv Rathee", tag: "Fact Check", origin: "India",
    stats: { power: 6, speed: 8, defense: 6 },
    specialName: "Fact Check Debunk Blast",
    specialDesc: "Holographic tablet fires an analytical white beam.",
    specialFx: "beam",
    palette: { skin: "#d1a17a", hair: "#1a1a1a", beard: "#2a1a10", outfit: "#2a4a8a", accent: "#e8e8f8" },
    build: "lean", accessory: "jacket" },

  // --- POP / HISTORICAL ---
  { id: "gandhi", name: "Mahatma Gandhi", tag: "Bapu", origin: "India",
    stats: { power: 5, speed: 7, defense: 9 },
    specialName: "Dandi March Dash",
    specialDesc: "Non-violent march summons spectral marchers in a dust wave.",
    specialFx: "marchDash",
    palette: { skin: "#c68b5a", hair: "#f0f0f0", beard: null, outfit: "#f4f0e6", accent: "#c8c0b0" },
    build: "gaunt", accessory: "dhoti" },
  { id: "godse", name: "Nathuram Godse", tag: "Vintage Shooter", origin: "India",
    stats: { power: 8, speed: 7, defense: 5 },
    specialName: "Gunslinger Precision",
    specialDesc: "Dual vintage revolvers, three-shot cinematic blast.",
    specialFx: "gunSlinger",
    palette: { skin: "#c68b5a", hair: "#1a1a1a", beard: null, outfit: "#3a2a1a", accent: "#8a6a2a" },
    build: "average", accessory: "vest" },
  { id: "emraan", name: "Emraan Hashmi", tag: "Serial Kisser", origin: "India",
    stats: { power: 6, speed: 8, defense: 6 },
    specialName: "Bheege Hoth Hypnosis",
    specialDesc: "Guitar riff + blue rain trance, ends with heart-burst.",
    specialFx: "rainTrance",
    palette: { skin: "#c99274", hair: "#1a1a1a", beard: "#2a1a10", outfit: "#1a1a2a", accent: "#c74a6a" },
    build: "average", accessory: "jacket" },
  { id: "acp", name: "ACP Pradyuman", tag: "CID", origin: "India",
    stats: { power: 9, speed: 5, defense: 8 },
    specialName: "Daya, Darwaza Tod",
    specialDesc: "Summons a wooden door and delivers a running slap through it.",
    specialFx: "doorSlap",
    palette: { skin: "#c68b5a", hair: "#e4e4e4", beard: "#dadada", outfit: "#6a4a2a", accent: "#3a2a1a" },
    build: "heavy", accessory: "suit" },
  { id: "dhoni", name: "MS Dhoni", tag: "Thala 7", origin: "India",
    stats: { power: 9, speed: 8, defense: 8 },
    specialName: "Thala For A Reason",
    specialDesc: "7-hit combo with a glowing bat, ends on a Helicopter Shot.",
    specialFx: "helicopter",
    palette: { skin: "#c68b5a", hair: "#1a1a1a", beard: "#2a1a10", outfit: "#f5c518", accent: "#1a3a8a" },
    build: "athletic", accessory: "jersey7" },
  { id: "salman", name: "Salman Khan", tag: "Bhoi", origin: "India",
    stats: { power: 10, speed: 6, defense: 8 },
    specialName: "Footpath Massacre",
    specialDesc: "Phantom SUV charges across the arena.",
    specialFx: "suvCharge",
    palette: { skin: "#d1a17a", hair: "#1a1a1a", beard: "#2a1a10", outfit: "#1a1a1a", accent: "#8a4a2a" },
    build: "muscular", accessory: "leatherJacket" },
  { id: "virat", name: "Virat Kohli", tag: "King", origin: "India",
    stats: { power: 8, speed: 9, defense: 7 },
    specialName: "Ben Stokes Verbal Burst",
    specialDesc: "Sonic shout + light-speed Cover Drive strike.",
    specialFx: "sonicShout",
    palette: { skin: "#c68b5a", hair: "#1a1a1a", beard: "#2a1a10", outfit: "#1a3a8a", accent: "#c74a4a" },
    build: "athletic", accessory: "jersey" },
  { id: "talwiinder", name: "Talwiinder", tag: "Underground", origin: "India",
    stats: { power: 6, speed: 8, defense: 6 },
    specialName: "Underground Echo Blast",
    specialDesc: "Bass-drop soundwaves float and explode the enemy.",
    specialFx: "bassDrop",
    palette: { skin: "#c68b5a", hair: "#1a1a1a", beard: null, outfit: "#2a2a3a", accent: "#4affc0" },
    build: "lean", accessory: "hoodie" },
  { id: "taylor", name: "Taylor Swift", tag: "Darji Swift", origin: "USA",
    stats: { power: 7, speed: 8, defense: 7 },
    specialName: "Blank Space Eras Tremor",
    specialDesc: "Stadium spotlights + musical note ring blast.",
    specialFx: "erasTour",
    palette: { skin: "#f0d0b0", hair: "#e8c060", beard: null, outfit: "#e8c8f0", accent: "#f8f0a0" },
    build: "slim", accessory: "gown" },

  // --- GLOBAL LEADERS ---
  { id: "kim", name: "Kim Jong Un", tag: "Rocket Man", origin: "DPRK",
    stats: { power: 9, speed: 4, defense: 9 },
    specialName: "Hwasong ICBM Blast",
    specialDesc: "Launches a cartoon ICBM that craters the enemy.",
    specialFx: "icbm",
    palette: { skin: "#e8c9a0", hair: "#1a1a1a", beard: null, outfit: "#1a1a2a", accent: "#8a3a3a" },
    build: "heavy", accessory: "maoSuit" },
  { id: "trump", name: "Donald Trump", tag: "45/47", origin: "USA",
    stats: { power: 8, speed: 5, defense: 8 },
    specialName: "The Great Wall Barrier",
    specialDesc: "Manifests a golden brick wall that launches the enemy.",
    specialFx: "wall",
    palette: { skin: "#f0b070", hair: "#e8c060", beard: null, outfit: "#1a2a5a", accent: "#c02020" },
    build: "broad", accessory: "redTie" },
  { id: "putin", name: "Vladimir Putin", tag: "Judo", origin: "RUS",
    stats: { power: 9, speed: 7, defense: 8 },
    specialName: "Siberian Bear Takedown",
    specialDesc: "Spectral bear slam + icy shockwave finisher.",
    specialFx: "bearSlam",
    palette: { skin: "#e8c9a0", hair: "#c8c0a8", beard: null, outfit: "#1a1a2a", accent: "#6a6a8a" },
    build: "compact", accessory: "suit" },
  { id: "zelensky", name: "Volodymyr Zelenskyy", tag: "Tactical", origin: "UKR",
    stats: { power: 7, speed: 8, defense: 7 },
    specialName: "Iron Shield Drone Barrage",
    specialDesc: "Drone strike volley bombards the enemy zone.",
    specialFx: "drones",
    palette: { skin: "#d8b090", hair: "#3a2a1a", beard: "#3a2a1a", outfit: "#4a5a3a", accent: "#2a3a2a" },
    build: "athletic", accessory: "tactical" },
  { id: "xi", name: "Xi Jinping", tag: "Chairman", origin: "CHN",
    stats: { power: 8, speed: 5, defense: 9 },
    specialName: "Dragon Belt & Road Strike",
    specialDesc: "Golden dragon circles then blasts through in a line.",
    specialFx: "dragon",
    palette: { skin: "#e8c9a0", hair: "#1a1a1a", beard: null, outfit: "#1a1a2a", accent: "#c8a020" },
    build: "broad", accessory: "suit" },
  { id: "takaichi", name: "Sanae Takaichi", tag: "Bushido", origin: "JPN",
    stats: { power: 7, speed: 9, defense: 6 },
    specialName: "Samurai Speed Slice",
    specialDesc: "Light-speed dash-through with cherry blossom cuts.",
    specialFx: "samurai",
    palette: { skin: "#f0d0b0", hair: "#1a1a1a", beard: null, outfit: "#8a1a2a", accent: "#f0e0e0" },
    build: "slim", accessory: "kimono" },
  { id: "meloni", name: "Giorgia Meloni", tag: "Roma", origin: "ITA",
    stats: { power: 7, speed: 7, defense: 7 },
    specialName: "Colosseum Roman Chariot",
    specialDesc: "Spectral Roman chariot stampede across the arena.",
    specialFx: "chariot",
    palette: { skin: "#e8c9a0", hair: "#c8a060", beard: null, outfit: "#2a2a2a", accent: "#c8a020" },
    build: "average", accessory: "suit" },
];

export const getFighter = (id) => ROSTER.find((f) => f.id === id) || ROSTER[0];
